---
deployment:
  tasks:
    - export DEPLOYPATH=${DEPLOYPATH:-/home/$USER/public_html}
    - export NODE_VERSION=16.14.0 # Set the Node.js version
    - echo "Deploying application to $DEPLOYPATH"

    - step: Install Node.js
      command: |
        if ! node -v | grep -q $NODE_VERSION; then
          echo "Installing Node.js $NODE_VERSION"
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
          . ~/.nvm/nvm.sh
          nvm install $NODE_VERSION
          nvm use $NODE_VERSION
          nvm alias default $NODE_VERSION
        fi

    - step: Install Dependencies
      command: |
        echo "Installing dependencies"
        npm install

    - step: Build Application
      command: |
        echo "Building the application"
        npm run build

    - step: Deploy Application
      command: |
        echo "Deploying the application"
        rsync -av --delete-after dist/ $DEPLOYPATH/
