---
deployment:
  tasks:
    - export DEPLOY_PATH=/home/thendo/public_html
    - export REPOSITORY_ROOT=/home/thendo/repositories/dev_site
    - /bin/sh:
        command: |
          set -e

          # Navigate to the repository root
          cd $REPOSITORY_ROOT

          # Install npm dependencies
          npm install

          # Build the Vite app
          npm run build

          # Remove old build files from the deploy path
          rm -rf $DEPLOY_PATH/*

          # Copy new build files to the deploy path
          cp -r dist/* $DEPLOY_PATH

# Additional settings (if needed)
