name: Deploy to cPanel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm install

      - name: Build Vite React App
        run: npm run build

      - name: Deploy via SFTP
        uses: ashutoshvarma/action-scp@v1
        with:
          local: dist/                # Local build directory
          remote: /public_html/       # Target directory on the server
          host: ${{ secrets.CPANEL_HOST }}
          username: ${{ secrets.CPANEL_USERNAME }}
          password: ${{ secrets.CPANEL_PASSWORD }}
          port: 22                    # Default port for SFTP
